name: feature/** vers dev 

on: 
  pull_request:
    branches:
      - dev

jobs:
  build:
    if: startsWith(${{github.head.ref}}, "feature/")
    name: Conventional Commits
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix: 
        version: [14, 16]
      runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.version}}

     