name: Upload Artifact

on: workflow_dispatch

jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      - name: stocker les fichers
      
        run: "coucou toi artifact"
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ci
          path: ci.txt
